---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 329367383-K1gZzaYxfsLxNPByYM9mdeewoBtwGfNgGwwHdON7
:access_token_secret: 6rv3ESbEdmwKn68PouYQkPs16Kvx4eLIiaQ1rDtdDPc70
